# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensors_wl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='as1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='as2',
            field=models.CharField(max_length=50),
        ),
    ]
