# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='dateAndTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
