# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_auto_20171102_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='as1',
            new_name='plant1_actuatorstate',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='ps1',
            new_name='plant1_soilmoisture',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='as2',
            new_name='plant2_actuatorstate',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='ps2',
            new_name='plant2_soilmoisture',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='wl',
            new_name='waterlevel',
        ),
    ]
