# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_auto_20171102_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilmoisture', models.FloatField(default=0)),
                ('actuatorstate', models.CharField(max_length=50)),
                ('dateAndTime', models.CharField(max_length=255)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('waterlevel', models.FloatField(default=0)),
                ('rainfall', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Sensors',
        ),
    ]
