# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_auto_20171109_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='plantId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sensors.a'),
        ),
        migrations.AddField(
            model_name='c',
            name='plantId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sensors.b'),
        ),
    ]
