# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_auto_20171109_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='name',
        ),
    ]
