# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_auto_20171110_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='plantId',
        ),
    ]
