# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_remove_b_plantid'),
    ]

    operations = [
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilmoisture', models.FloatField(default=0)),
                ('actuatorstate', models.CharField(max_length=50)),
                ('dateAndTime', models.CharField(max_length=255)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('waterlevel', models.FloatField(default=0)),
                ('rainfall', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='b',
            name='plantId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sensors.a'),
        ),
        migrations.AddField(
            model_name='c',
            name='plantId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sensors.b'),
        ),
    ]
