# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_auto_20171110_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c',
            new_name='plantdetails',
        ),
        migrations.RenameModel(
            old_name='b',
            new_name='plantid',
        ),
        migrations.RenameModel(
            old_name='a',
            new_name='stationlocation',
        ),
    ]
