# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_auto_20171121_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdetails',
            old_name='plantId',
            new_name='idOfPlant',
        ),
    ]
