# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0023_auto_20171122_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plantid',
            new_name='plant',
        ),
    ]
