# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_auto_20171122_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorstate', models.FloatField(default=0)),
            ],
        ),
    ]
