# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0025_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetails',
            name='ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='msdisplay',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
